<?php

/**
 * EggTheft – EggTheft.php
 *
 * Copyright (C) 2017 Jack Noordhuis
 *
 * This is private software, you cannot redistribute and/or modify it in any way
 * unless given explicit permission to do so. If you have not been given explicit
 * permission to view or modify this software you should take the appropriate actions
 * to remove this software from your device immediately.
 *
 * @author Jack Noordhuis
 *
 * Created on 13/8/17 at 7:41 PM
 *
 */

namespace conflict\eggtheft;

use pocketmine\plugin\PluginBase;

class EggTheft extends PluginBase {

	const MAP_CONFIG = "maps.json";
	const SETTINGS_CONFIG = "settings.yml";

	public function onEnable() {
		$this->loadConfigs();
	}

	public function loadConfigs() {
		if(!is_dir($this->getDataFolder())) {
			mkdir($this->getDataFolder(), 777);
			$this->saveResource(self::MAP_CONFIG);
			$this->saveResource(self::SETTINGS_CONFIG);
		}
	}

	public function onDisable() {
		parent::onDisable(); // TODO: Change the autogenerated stub
	}

}